// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"personal-project-core/config"
	"personal-project-core/context"
	"personal-project-core/services/database"
	"personal-project-core/services/log"
	"personal-project-core/services/server"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	logger := log.NewZapLogger()
	db, err := database.NewPostgresConnection(configConfig)
	if err != nil {
		return nil, err
	}
	serviceContext := context.NewServiceContext(configConfig, logger, db)
	serverServer := server.NewServer(serviceContext)
	return serverServer, nil
}
