openapi: 3.0.0
info:
  title: User API
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server

paths:
  /login:
    $ref: "./auth/api.yaml#/paths/~1auth~1login"